
# @package _global_
resume:
save_dir: models/
log_dir: ${name}/

metrics:
  - _target_: srcs.model.metric.accuracy
  - _target_: srcs.model.metric.top_k_acc

defaults:
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train

  - override hydra/job_logging : custom
  # Problem in the config of hydra/run/dir. 
  # TODO: Fix this error
  # - override hydra/run/dir: job_timestamp
  # - override hydra/run: job_timestamp